/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/freshman": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取新人列表 */
    get: operations["get_FreshmanList"]
    put?: never
    /** 添加新人 */
    post: operations["post_FreshmanAdd"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_FreshmanList: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns a list of tasks */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            success: boolean
            list: {
              /** @example lorem */
              name: string
              /** @example 3240000000 */
              number: string
              /** @example 计算机科学与技术 */
              major: string
              /** @example 计科2001 */
              class: string
              /** @example xxx@qq.com */
              email: string
              /** @example 12345678901 */
              phone: string
              /** @example 123456789 */
              qq: string
            }[]
          }
        }
      }
    }
  }
  post_FreshmanAdd: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "application/json": {
          /** @example lorem */
          name: string
          /** @example 3240000000 */
          number: string
          /** @example 计算机科学与技术 */
          major: string
          /** @example 计科2001 */
          class: string
          /** @example xxx@qq.com */
          email: string
          /** @example 12345678901 */
          phone: string
          /** @example 123456789 */
          qq: string
        }
      }
    }
    responses: {
      /** @description Returns the created task */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            success: boolean
            result?: {
              /** @example lorem */
              name: string
              /** @example 3240000000 */
              number: string
              /** @example 计算机科学与技术 */
              major: string
              /** @example 计科2001 */
              class: string
              /** @example xxx@qq.com */
              email: string
              /** @example 12345678901 */
              phone: string
              /** @example 123456789 */
              qq: string
            }
            error?: string
          }
        }
      }
    }
  }
}
