// This file is auto-generated by @hey-api/openapi-ts

export type PostFreshmanAddData = {
  requestBody?: {
    name: string;
    number: string;
    major: string;
    class: string;
    email: string;
    phone: string;
    qq: string;
  };
};

export type PostFreshmanAddResponse = {
  success: boolean;
  result?: {
    name: string;
    number: string;
    major: string;
    class: string;
    email: string;
    phone: string;
    qq: string;
  };
  error?: string;
};

export type GetFreshmanListResponse = {
  success: boolean;
  list: Array<{
    name: string;
    number: string;
    major: string;
    class: string;
    email: string;
    phone: string;
    qq: string;
  }>;
};
